<a href="https://colab.research.google.com/github/RITESH-CHAUHAN2005/AI-Python/blob/main/Session_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Agenda
#Pandas(Library)
#BlackBox (Magic box)
import pandas as pd

In [ ]:
a = pd.read_csv('/content/color_srgb.csv')
a

       Name      HEX               RGB
0     White  #FFFFFF  rgb(100,100,100)
1    Silver  #C0C0C0     rgb(75,75,75)
2      Gray  #808080     rgb(50,50,50)
3     Black  #000000        rgb(0,0,0)
4       Red  #FF0000      rgb(100,0,0)
5    Maroon  #800000       rgb(50,0,0)
6    Yellow  #FFFF00    rgb(100,100,0)
7     Olive  #808000      rgb(50,50,0)
8      Lime  #00FF00      rgb(0,100,0)
9     Green  #008000       rgb(0,50,0)
10     Aqua  #00FFFF    rgb(0,100,100)
11     Teal  #008080      rgb(0,50,50)
12     Blue  #0000FF      rgb(0,0,100)
13     Navy  #000080       rgb(0,0,50)
14  Fuchsia  #FF00FF    rgb(100,0,100)
15   Purple  #800080      rgb(50,0,50)

In [ ]:
a.info()#information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    16 non-null     object
 1   HEX     16 non-null     object
 2   RGB     16 non-null     object
dtypes: object(3)
memory usage: 516.0+ bytes

In [ ]:
a.describe()

         Name      HEX               RGB
count      16       16                16
unique     16       16                16
top     White  #FFFFFF  rgb(100,100,100)
freq        1        1                 1

In [ ]:
a.isnull().sum()

Name    0
HEX     0
RGB     0
dtype: int64

In [ ]:
df = pd.read_csv("/content/Unclean Dataset.csv", encoding='latin1')
df.head()

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,Student_ID,First_Name,Last_Name,Age,Gender,Course,Enrollment_Date,Total_Payments
0,101 | John | Smith | 22 | M ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,102 | Emily | Johnson | 24 | F ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,103 | Michael | Williams | 21 | M ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,104 | Sarah | Brown | 23 | F ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105 | David | Davis | 20 | M ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns = df.columns.str.strip()
df_split = df['Student_ID'].str.split(' | ', expand=True)

df['Student_ID'] = pd.to_numeric(df_split[0].str.strip(), errors='coerce').astype('Int64')
df['First_Name'] = df_split[1].str.strip()
df['Last_Name'] = df_split[2].str.strip()
df['Age'] = pd.to_numeric(df_split[3].str.strip(), errors='coerce').astype('Int64')
df['Gender'] = df_split[4].str.strip()
df['Course'] = df_split[5].str.strip()
df['Enrollment_Date'] = pd.to_datetime(df_split[6].str.strip(), errors='coerce')
df['Total_Payments'] = pd.to_numeric(df_split[7].str.replace('$', '', regex=False).str.strip(), errors='coerce')

/tmp/ipykernel_12506/3401847426.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Enrollment_Date'] = pd.to_datetime(df_split[6].str.strip(), errors='coerce')

Now that we've extracted and assigned the values, let's look at the first few rows of the cleaned DataFrame `df` and its information to confirm the changes.

In [ ]:
display(df.head())
display(df.info())

,Student_ID,First_Name,Last_Name,Age,Gender,Course,Enrollment_Date,Total_Payments
0,101 | John | Smith | 22 | M ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,102 | Emily | Johnson | 24 | F ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,103 | Michael | Williams | 21 | M ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,104 | Sarah | Brown | 23 | F ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105 | David | Davis | 20 | M ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student_ID         132 non-null    object
 1    First_Name        99 non-null     object
 2    Last_Name         18 non-null     object
 3    Age               53 non-null     object
 4    Gender            59 non-null     object
 5    Course            54 non-null     object
 6    Enrollment_Date   60 non-null     object
 7    Total_Payments    58 non-null     object
dtypes: object(8)
memory usage: 8.6+ KB

None

In [ ]:
df.columns

Index(['Student_ID ', ' First_Name ', ' Last_Name ', ' Age ', ' Gender ',
       ' Course ', ' Enrollment_Date ', ' Total_Payments'],
      dtype='object')

In [ ]:
df['Student_ID ']

0      101        | John       | Smith     | 22  | M ...
1      102        | Emily      | Johnson   | 24  | F ...
2      103        | Michael    | Williams  | 21  | M ...
3      104        | Sarah      | Brown     | 23  | F ...
4      105        | David      | Davis     | 20  | M ...
                             ...
131    232        | Amina      | Adekunle    | 21  | ...
132    234       | Ibrahim    | Okafor      | 22  | M...
133    235        | Zainab     | Abiodun     | 23  | ...
134    236        | Nasiru     | Adebayo     | 24  | ...
135    237       | Aisha      | Okonkwo     | 25  | F...
Name: Student_ID , Length: 136, dtype: object

In [ ]:
df['Student_ID '][0]

'101        | John       | Smith     | 22  | M      | Data Science   | 2022-05-15      | $1200'

In [ ]:
int (df['Student_ID '][0].split(" | ")[0].strip())

101

In [ ]:
df.columns[0].strip()

'Student_ID'

In [ ]:
df = df.rename(columns={'Student_ID ': 'Student_ID', ' First_Name ': 'First_Name', ' Last_Name ': 'Last_Name', ' Age ':'Age', ' Gender ' : 'Gender', ' Course ' : "Course",' Enrollment_Date ': 'Enrollment_Date',' Total_Payments': 'Total_Payments'  })

In [ ]:
df.columns

Index(['Student_ID', 'First_Name', 'Last_Name', 'Age', 'Gender', 'Course',
       'Enrollment_Date', 'Total_Payments'],
      dtype='object')

In [ ]:
df

,Student_ID,First_Name,Last_Name,Age,Gender,Course,Enrollment_Date,Total_Payments
0,101,,,<NA>,,,NaT,NaN
1,102,,,<NA>,,,NaT,NaN
2,103,,,<NA>,,,NaT,NaN
3,104,,,<NA>,,,NaT,NaN
4,105,,,<NA>,,,NaT,NaN
...,...,...,...,...,...,...,...,...
131,232,,,<NA>,,,NaT,NaN
132,234,,,<NA>,,,NaT,NaN
133,235,,,<NA>,,,NaT,NaN
134,236,,,<NA>,,,NaT,NaN
135,237,,,<NA>,,,NaT,NaN